<?php echo $this->doctype() ?>
<html lang="en">
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle('Developer Resources | ') ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>

<?php
if (Model_Kwgldev_Layout::isPaginationTemplateRequired()) {
	echo $this->render('_templates/template_pagination.phtml');
}
?>
	</head>
	<body>
<?php
	$aPartial = array('partials/navigation.phtml', 'kwgldev');
	$this->navigation()->menu()->setPartial($aPartial);
?>
		<div class="cContainer" id="iDivNavigationContainer">
			<div class="cRow">
				<div class="cSpan12 cNavigationBar"><?php echo $this->navigation()->menu()->render(); ?></div>
			</div>
		</div>

		<div class="cContainer" id="iDivBodyContainer">
			<div class="cRow">
				<div class="cSpan12"><?php echo $this->layout()->content; ?></div>
			</div>
		</div>

	</body>
</html>