<?php
$aContent = $this->aContent;
$aContent['response'][] = array('status' => 'error', 'message' => 'Your form submission contains errors. Your form submission contains errors. Please correct them and re-submit.', 'detail' => 'Your form submission contains errors. Please correct them and re-submit. Your form submission contains errors. Please correct them and re-submit.');
$aContent['response'][] = array('status' => 'successful', 'message' => 'Your form submission contains errors. Your form submission contains errors. Please correct them and re-submit.', 'detail' => 'Your form submission contains errors. Please correct them and re-submit. Your form submission contains errors. Please correct them and re-submit.');


?>
<h2>Dashboard</h2>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
<?php// echo $this->partial('/partials/response.phtml', array('aResponse' => $aContent['response'])); ?>
