<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
	<div id="iDivContainer">
		<div id="iDivLoginHeader"><h1>Shares - Administration</h1></div>
		<div id="iDivLoginOuterContainer">
			<?php echo $this->layout()->content; ?>
		</div>
	</div>
</body>
</html>