<?php
// Change these

 
// Congratulations! You have a valid token. Now fetch your profile 
$user = Model_LinkedIn::fetch('GET', '/v1/people/~:(firstName,lastName)');
Zend_Debug::dump($user);

$connections = Model_LinkedIn::fetch('GET', '/v1/people/~/connections:(first-name,last-name)');
// test
// test 2
Zend_Debug::dump($connections);

//print "Hello $user->firstName $user->lastName.";
//exit;
 

     

 
