<?php
// Change these

 
// Congratulations! You have a valid token. Now fetch your profile 

?>
<h1>Cause</h1>

<div class="wrap-er">
  <div class="descirption">
    <img src="/img/miami.jpg" >
    <p>One Laptop per Child creates educational opportunities for the word's poorest children living in the most remote places on Earth, by providing each child with a rugged, solar-powered, connected laptop with content and software designed for collaborative, joyful, self-empowered learning.</p>
  </div>

  <div class="callToAction">
    <a class="btn btn-large btn-success" href="/donate/index">Donate!</a>
  </div>
</div>
