<?php
// Change these

 
// Congratulations! You have a valid token. Now fetch your profile 

?>
 <div class="wrap">
      <div class="container landing">
        <div class="header">
          <h1>One laptop per child</h1>
        </div>
        <div class="row content">
          <div>
            <ul class="thumbnails centerimage">
              <li>
                <a href="#" class="thumbnail">
                  <img src="/img/miami.jpg" alt="">
                </a>
              </li>
            </ul>
            <div class="explanation">
              <p>One Laptop per Child creates educational opportunities for the word's poorest children living in the most remote places on Earth, by providing each child with a rugged, solar-powered, connected laptop with content and software designed for collaborative, joyful, self-empowered learning.</p>
            </div>
          </div>
          <div class="donate">
            <a class="btn btn-success btn-large" href="/donate/index">Donate Now</a>
          </div>
        </div>

      </div>
    </div>
