<?php
$aContent = $this->aContent;
?>
<h1><?php echo $aContent['header']; ?></h1>
<p><?php echo $aContent['message']; ?></p>
<?php if (isset($aContent['trace'])) { ?><pre><?php echo $aContent['trace']; ?></pre><?php } ?>
<?php if (isset($aContent['sql'])) { ?><pre><?php echo $aContent['sql']; ?></pre><?php } ?>
<!--
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php endif ?>

-->