<?php echo $this->doctype() ?>
<html lang="en">
	<head>
    <script src="/js/library/underscore-min.js"></script>
    <script src="/js/library/jquery-1.7.2.min.js"></script>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle() ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>
    <link rel="stylesheet" type="text/css" href="/css/library/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/library/bootstrap/bootstrap-responsive.min.css">
    <link rel="stylesheet" type="text/css" href="/css/default/bubble.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/payment.css">
        </head>
	<body>
    <script src="/js/highcharts.js"></script>
    <script src="/js/exporting.js"></script>
		<div id="iDivContainer" class="container">
			<?php echo $this->layout()->content; ?>
		</div>
	</body>
</html>
