<?php echo $this->doctype() ?>
<html lang="en">
	<head>
    <script src="/js/library/jquery-1.7.2.min.js"></script>
    <script src="//cdn.jsdelivr.net/underscorejs/1.4.3/underscore-min.js"></script>
    <script src="/js/visualization.js"></script>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle() ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>
    <link rel="stylesheet" type="text/css" href="/css/library/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/library/bootstrap/bootstrap-responsive.min.css">
	</head>
	<body>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/modules/exporting.js"></script>
		<div id="iDivContainer" class="container">
			<?php echo $this->layout()->content; ?>
		</div>
	</body>
</html>
