<?php
$sResponse = Zend_Registry::get('Authentication Response');
switch ($sResponse) {
	case 'login-failed':
		?>
<p class="cPLoginResponse">Your login attempt has failed. We could not verify you as a registered member. Please try again.</p>
		<?php
		break;
	case 'login-invalid':
		?>
<p class="cPLoginResponse">Your did not provide the necessary information. Provide both your Username & Password and please try again.</p>
		<?php
		break;
}
?>
<div id="iDivLoginContainer">
	<h2>Login</h2>
	<p id="iPForgotPassword"><a href="#">Forgot Password?</a></p>
	<form action="<?php echo $this->element->getAction();?>" method="<?php echo $this->element->getMethod(); ?>" id="<?php echo $this->element->getAttrib("id"); ?>" enctype="<?php echo $this->element->getAttrib("enctype"); ?>" accept-charset="utf-8">
		<div id="iDivUsername">
			<label class="smallInput">Email:</label><br />
			<span><?php echo $this->element->textEmail; ?></span>
		</div>
		<div id="iDivPassword">
			<label class="smallInput">Password:</label><br />
			<span><?php echo $this->element->passwordPassword; ?></span>
		</div>
		<div id="iDivSubmit">
			&nbsp;<?php echo $this->element->submitLogin; ?>
		</div>
	</form>
</div>