<form action="/donate/index" method="POST" autocomplete="off">
  <label>Amount: <input name="money" type="number" min="1.0" step="1" value="5" /> </label>
  <br/>
  <label>Card number: <input name="number" type="text"> </lable>
  <br/>
  <label>Expiration date: </lable>
  <br/>
  <label>year:
    <select>
      <option value="2013">2013</option>
      <option value="2014">2014</option>
      <option value="2015">2015</option>
      <option value="2016">2016</option>
      <option value="2017">2017</option>
      <option value="2018">2018</option>
    </select>
  </lable>
  <br/>
  <label>month:
    <select>
      <option value="01">01</option>
      <option value="02">02</option>
      <option value="03">03</option>
      <option value="04">04</option>
      <option value="05">05</option>
      <option value="06">06</option>
      <option value="07">07</option>
      <option value="08">08</option>
      <option value="09">09</option>
      <option value="10">10</option>
      <option value="11">11</option>
      <option value="12">12</option>
    </select>
  </lable>
  <br/>
  <input class="btn btn-large" type="submit" value="Gimme money!">
</form>
