 <div class="wrap">
      <div class="container landing">
        <div class="header">
          <h1>TNW Project</h1>
          <h2><small>Crowd funding in real.</small></h2>
        </div>

        <div class="content">
          <form class="custom" action="/donate/index" method="post">

            <p>Donation</p>
            <p><input class="span4" type="text" name="money" placeholder=" $ Enter amount" value=""></p>

            <p>Payment</p>
            <p>
              <input class="span4" type="text" name="chard-number" placeholder="Card number" value="">
              <br/>
              <input class="span2 small" type="text" name="exp" placeholder="exp" value="">
              <input class="span2 small" type="text" name="exp" placeholder="cvs" value="">
            </p>

            <p><input class="btn btn-success btn-large" type="submit" value="Validate Payment"></p>

        </form>
        </div>

      </div>
    </div>
